version: '3'

services:
  web:
    build: .
    volumes:
    - .:/opt/project
    - ./data:/data
    ports:
    - 8000:80
    - 3000:3000
    depends_on:
    - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
    - 13306:3306
